version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: tpv-postgres
    restart: always
    environment:
      POSTGRES_USER: tpvadmin
      POSTGRES_PASSWORD: tpv1234
      POSTGRES_DB: tpvdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - tpv_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: tpv-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tpv.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  tpv_data:
